# Открываем стандартный порт для внешних подключений
listener 1883  0.0.0.0

listener_allow_anonymous false
password_file /mosquitto/config/password.txt

# Пути для сохранения логов и данных внутри контейнера
persistence true
persistence_location /mosquitto/data/
log_type all
log_dest file /mosquitto/log/mosquitto.log
