mqtt:
  server: "tcp://mosquitto:1883"

  # Optional: for TLS client certificates
  #  ca_cert: certs/AmazonRootCA1.pem
  #  client_cert: certs/xxxxx-certificate.pem.crt
  #  client_key: certs/xxxxx-private.pem.key

  topic_path: +/+/+/telemetry
  device_id_regex: "(?P<vehicle_type>[^/]+)/(?P<fuel_type>[^/]+)/(?P<deviceid>[^/]+)/telemetry"
  qos: 0
  object_per_topic_config:
    encoding: JSON
cache:
  timeout: 24h
  state_directory: "/var/lib/mqtt2prometheus"
json_parsing:
  separator: .

metrics:
  - prom_name: mqtt_speed
    mqtt_name: metrics.speed_kmh
    help: Speed of vehicle
    type: gauge
  - prom_name: mqtt_lat
    mqtt_name: metrics.gps_lat
    help: Latitude of vehicle
    type: gauge
  - prom_name: mqtt_lon
    mqtt_name: metrics.gps_lon
    help: Longitude of vehicle
    type: gauge
