[dashboards]
default_home_dashboard_path = /etc/grafana/dashboards/tractor_details.json
[smtp]
enabled = true
host = smtp.yandex.ru:465
# Grafana will dynamically read these variables from your compose file environment
user = ${GF_SMTP_USER}
password = ${GF_SMTP_PASSWORD}
skip_verify = false
from_address = ${GF_SMTP_FROM_ADDRESS}
from_name = ${GF_SMTP_FROM_NAME}