# my global config
global:
  scrape_interval: 2s
  evaluation_interval: 2s 
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # Prometheus exposes data about itself as an HTTP endpoint, it scrapes and monitors its own health
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
       # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"

  - job_name: "vehicles"
    static_configs:
      - targets: ["mqtt-exporter:9641"]
    metric_relabel_configs:
      - source_labels: [__name__, topic]
        regex: "^speed;([^/]+)/([^/]+)/([^/]+)/telemetry$"
        target_label: vehicle_type
        replacement: "${1}"
        action: replace
      - source_labels: [__name__, topic]
        regex: "^speed;([^/]+)/([^/]+)/([^/]+)/telemetry$"
        target_label: fuel_type
        replacement: "${2}"
        action: replace
      - source_labels: [__name__, topic]
        regex: "^speed;([^/]+)/([^/]+)/([^/]+)/telemetry$"
        target_label: deviceid
        replacement: "${3}"
        action: replace

