global:
  scrape_interval: 2s
  evaluation_interval: 2s 
  # scrape_timeout is set to the global default (10s).

remote_write:
  - url: "http://victoriametrics:8428/api/v1/write"
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
      
  # Prometheus exposes data about itself as an HTTP endpoint, it scrapes and monitors its own health
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "vehicles"
    static_configs:
      - targets: ["mqtt-exporter:9641"]
    metric_relabel_configs:
      - source_labels: [__name__, topic]
        # Matches: mqtt_anyname;vehicle_type/fuel_type/vehicle_id/telemetry
        regex: "^(mqtt_[^;]+);([^/]+)/([^/]+)/([^/]+)/telemetry$"
        target_label: vehicle_type
        replacement: "${2}"
        action: replace

      - source_labels: [__name__, topic]
        regex: "^(mqtt_[^;]+);([^/]+)/([^/]+)/([^/]+)/telemetry$"
        target_label: fuel_type
        replacement: "${3}"
        action: replace

      - source_labels: [__name__, topic]
        regex: "^(mqtt_[^;]+);([^/]+)/([^/]+)/([^/]+)/telemetry$"
        target_label: vehicle_id
        replacement: "${4}"
        action: replace

      - regex: "^sensor$"
        action: labeldrop


