apiVersion: 1
groups:
    - orgId: 1
      name: robot-eg
      folder: Robot alerts
      interval: 10s
      rules:
        - uid: afs6uzm7idvr4b
          title: Перегрев ЦПУ робота
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P4169E866C3094E38
              model:
                editorMode: code
                expr: mqtt_temp_cpu_c{vehicle_type="robot"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 85
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: park_state
          panelId: 12
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            __dashboardUid__: park_state
            __panelId__: "12"
          labels:
            severity: critical
            vehicle_type: robot
          isPaused: false
          notification_settings:
            receiver: telegram
