{
 "title": "Backend FMS метрики",
 "tags": [ "backend" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Количество успешно обработанных пакетов телеметрии из MQTT",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fms_telemetry_packets_processed_total",
     "legendFormat": "{{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Количество отброшенных пакетов телеметрии из-за ошибок парсинга",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fms_telemetry_packets_dropped_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общее количество обработанных HTTP запросов к FMS API",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fms_http_requests_total", "legendFormat": "{{l__name__}} {{method}}" }
   ]
  },
  {
   "title": "Время обработки HTTP запросов бэкендом FMS",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(fms_http_request_duration_seconds_bucket{status=\"200\"}[$__range])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}