{
 "title": "Мониторинг транспорта",
 "tags": [
  "fleet",
  "telemetry"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vehicle",
    "label": "Машина",
    "query": {
     "query": "label_values(mqtt_speed, vehicle_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Карта перемещения транспорта (Fleet Track)",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mqtt_lat{vehicle_id=~\"$vehicle\"}"
    },
    {
     "expr": "mqtt_lon{vehicle_id=~\"$vehicle\"}"
    }
   ]
  },
  {
   "title": "Текущая скорость",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_speed{vehicle_id=~\"$vehicle\"}"
    }
   ]
  },
  {
   "title": "Обороты двигателя",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_engine_rpm{vehicle_id=~\"$vehicle\"}"
    }
   ]
  }
 ]
}