{
 "title": "Детальный статус трактора",
 "tags": [ "tractor" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vid",
    "label": "tractor ID",
    "query": {
     "query": "label_values({vehicle_type=\"tractor\"},vehicle_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Вкл/выкл ТС",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_engine_status{vehicle_id=~\"$vid\", vehicle_type=~\"tractor\"}",
     "legendFormat": "{{vehicle_id}}-{{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Скорость по времени",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "mqtt_speed{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "tractor-{{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Вкл/выкл трактора по времени",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "mqtt_engine_status{vehicle_id=~\"$vid\", vehicle_type=~\"tractor\"}",
     "legendFormat": "{{vehicle_id}}-{{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Время работы (в часах) двигателей",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_engine_hours{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "tractor-{{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Уровень топлива",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_diesel_fuel_level_pct{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "tractor-{{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Температура двигателя",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_diesel_temp_c{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "tractor-{{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Обороты двигателей",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_diesel_engine_rpm{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "tractor-{{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Давление масла в двигателе",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_oil_pressure_bar{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "tractor-{{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Местонахождение",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "mqtt_lat{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mqtt_lon{vehicle_type=\"tractor\", vehicle_id=~\"$vid\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}