{
 "title": "Состояние парка",
 "tags": [
  "fleet",
  "telemetry"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "vid", "label": "ID TC", "query": { "query": "label_values(vehicle_id)" } },
   { "name": "vehicle_type", "label": "Тип ТС", "query": { "query": "label_values(vehicle_type)" } }
  ]
 },
 "panels": [
  { "title": "Метрики общие", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Скорость ТС",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_speed{vehicle_id=~\"$vid\", vehicle_type=~\"$vehicle_type\"}",
     "legendFormat": "{{vehicle_id}}-{{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Вкл/выкл ТС",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_engine_status{vehicle_id=~\"$vid\", vehicle_type=~\"$vehicle_type\"}",
     "legendFormat": "{{vehicle_id}}-{{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Карта перемещения ТС (Fleet Track)",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "mqtt_lat{vehicle_id=~\"$vid\"}",
     "legendFormat": "{{vehicle_id}}"
    },
    {
     "expr": "mqtt_lon{vehicle_id=~\"$vid\"}"
    }
   ]
  },
  { "title": "Электрическая техника", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Уровень батареи",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mqtt_electric_battery_soc_pct{fuel_type=\"electric\", vehicle_id=~\"$vid\"}",
     "legendFormat": "{{vehicle_id}} {{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Температура батареи",
   "type": "stat",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_electric_battery_temp_c{fuel_type=\"electric\", vehicle_id=~\"$vid\"}",
     "legendFormat": "{{vehicle_id}} {{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Уровень тока",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "mqtt_electric_current_a{fuel_type=\"electric\", vehicle_id=~\"$vid\"}",
     "legendFormat": "id:{{vehicle_id}} {{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Напряжение",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 11, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "mqtt_electric_voltage_v{fuel_type=\"electric\", vehicle_id=~\"$vid\"}",
     "legendFormat": "id:{{vehicle_id}} {{vehicle_type}}"
    }
   ]
  },
  { "title": "Роботы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Температура ЦПУ робота",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mqtt_robot_temp_cpu_c{vehicle_id=~\"$vid\", vehicle_type=\"robot\"}",
     "legendFormat": "{{vehicle_id}} {{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Вкл/выкл робота",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_engine_status{vehicle_id=~\"$vid\", vehicle_type=\"robot\"}",
     "legendFormat": "{{vehicle_id}}-{{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Oбщий показатель мощности радиосигнала",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mqtt_robot_lte_rssi{vehicle_id=~\"$vid\", vehicle_type=\"robot\"}",
     "legendFormat": "{{vehicle_id}} {{vehicle_type}}"
    }
   ]
  },
  {
   "title": "RTK статус робота",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_engine_status{vehicle_id=~\"$vid\", vehicle_type=\"robot\"}",
     "legendFormat": "{{vehicle_id}}-{{vehicle_type}}"
    }
   ]
  },
  {
   "title": "Статус миссии",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mqtt_robot_mission_status{vehicle_id=~\"$vid\"}",
     "legendFormat": "Robot {{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Угол поворота рулевого колеса",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "mqtt_robot_steering_angle_deg{vehicle_type=\"robot\", vehicle_id=~\"$vid\"}",
     "legendFormat": "id:{{vehicle_id}} {{vehicle_type}}"
    }
   ]
  }
 ]
}