server {
    listen 80;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    server_name mymeddata.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name mymeddata.ru;

    ssl_certificate /etc/letsencrypt/live/mymeddata.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mymeddata.ru/privkey.pem;

    location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /backend/api/v1/fleet/status {
        proxy_pass http://backend:8080/api/v1/fleet/status;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ========================================================
    # ЗАКРЫТЫЕ ЗОНЫ (Доступ только по логину и паролю)
    # ========================================================
    location /prometheus/ {
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://prometheus:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    location /backend {
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://backend:8080/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /mqtt_exporter {
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://mqtt-exporter:9641/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /victoriametrics {
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://victoriametrics:8428/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
