name: Infrastructure Destroy

# Триггер workflow_dispatch включает кнопку "Run workflow" в интерфейсе GitHub
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terra
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Save Yandex Cloud Key
      run: echo '${{ secrets.YC_SA_KEY }}' > key.json

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: >
        terraform destroy -auto-approve
