name: Infrastructure Destroy

# Триггер workflow_dispatch включает кнопку "Run workflow" в интерфейсе GitHub
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terra
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Save Yandex Cloud Key
      run: echo '${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}' > key.json

    - name: Terraform Init
      run: terraform init

    # Вроде как можно без переменных можно запустить команду. Но проверю после сдачи, когда отключу вм
    - name: Terraform Destroy
      run: >
        terraform destroy -auto-approve
        -var="cloud_id=${{ secrets.YC_CLOUD_ID }}"
        -var="folder_id=${{ secrets.YC_FOLDER_ID }}"
        -var="github_user=${{ github.actor }}"
        -var="github_token=${{ secrets.GITHUB_TOKEN }}"
        -var="github_repo=${{ github.event.repository.name }}"
        -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        -var="tg_bot_token=${{ secrets.TELEGRAM_BOT_TOKEN }}"
        -var="tg_chat_id=${{ secrets.TELEGRAM_CHAT_ID }}"
        -var="mqtt_broker_url=${{ secrets.MQTT_BROKER_URL }}"
        -var="mqtt_user=${{ secrets.MQTT_USER }}"
        -var="mqtt_pass=${{ secrets.MQTT_PASS }}"
        -var="fleet_backend_url=${{ secrets.FLEET_BACKEND_URL }}"
        -var="grafana_admin_pass=${{ secrets.GRAFANA_ADMIN_PASSWORD }}"
        -var="grafana_admin_name=${{ secrets.GRAFANA_ADMIN_NAME }}"
        -var="grafana_admin_email=${{ secrets.GRAFANA_ADMIN_EMAIL }}"
        -var="postgres_uri=${{ secrets.POSTGRES_URI }}"
        -var="postgres_db=${{ secrets.POSTGRES_DB }}"
        -var="postgres_user=${{ secrets.POSTGRES_USER }}"
        -var="postgres_pass=${{ secrets.POSTGRES_PASSWORD }}"
        -var="nginx_htpasswd_content=${{ secrets.NGINX_HTPASSWD_CONTENT }}"
        -var="mqqt_broker_passwd_content=${{ secrets.MQQT_BROKER_PASSWD_CONTENT }}"
